### PR TITLE
feat: login enable password and add cursor-pointer

### PR DESCRIPTION
**Pull request by louisyoungx**
1. Now can add password in `src/configs/user.ts`
- password is `''`by default
- if the password is null , the login behavior is the same as before
- if set the user.password, then you need to input the correct password to login

2. I found the login buttons haven't `cursor: pointer`, I have OCD😂, so I add it

### CODE REVIEW

**Comment by Renovamen** [comment]
Looks greate, thanks!

**Comment by louisyoungx** [comment]
> Looks greate, thanks!

谢谢，看了你的资料，太强了，我现在是你的超级粉丝🎉🎉🎉

**Comment by Renovamen** [comment]
> 谢谢，看了你的资料，太强了，我现在是你的超级粉丝🎉🎉🎉

啊非常感谢，我会继续努力的 😂

**Comment by bhaktatejas922** [comment]
## 🤖 AI Preview Test

Hey! We noticed you're doing amazing open source work. We built an AI model that's really good at testing web applications, so we ran it on your preview deployment to help catch any issues.

**Preview URL:** https://playground-macos-git-fork-louisyoungx-main-renovamen.vercel.app

### What We Found
✅ Preview deployment detected and queued for testing.

---
**Want unlimited free access?** We'd love to support your project with free AI-powered testing!

If you'd rather we not comment on your PRs, just 👎 this message and we'll remove you from our list.

<sub>Automated by [Morph](https://morphllm.com) • [Learn more](https://morphllm.com/docs/preview-testing)</sub>

**Pull request merged**
